### ISSUE TITLE
There is warning "Warning: Duplicate nodename <nodename> found in package <node package>", when validate locally

### ISSUE THREAD

**Issue by jatu-studiobox** [node-red/node-red-dev-cli#19]
When run "node-red-dev validate" on local, There is an warning message below.

```
Warning: Duplicate nodename <nodename> found in package <node package>
```

**Issue Reference :** 

[https://discourse.nodered.org/t/introducing-node-scorecards-and-a-new-node-naming-convention/57559/30](https://discourse.nodered.org/t/introducing-node-scorecards-and-a-new-node-naming-convention/57559/30) 
at question No.2

[https://discourse.nodered.org/t/introducing-node-scorecards-and-a-new-node-naming-convention/57559/31](https://discourse.nodered.org/t/introducing-node-scorecards-and-a-new-node-naming-convention/57559/31)
at Answer for question No.2

**Comment by sammachin** [comment]
Did you change the name of the package in package.json for you local version compared to what had already been published?

**Comment by jatu-studiobox** [comment]
> Did you change the name of the package in package.json for you local version compared to what had already been published?

Yes, I added more "@scopemane" to my package, such as "@myscope/packagename",  in package.json for my local version.

And yes, before validation, I had already published my project to npm. My project on npm has only 'packagename' in package.json.

**Comment by knolleary** [comment]
Then this is working as designed.

If you have renamed the package locally then the tool doesn't know you have previously published it under a different name. So it finds the module under its old name and warns of the duplicate.

**Comment by jatu-studiobox** [comment]
Ok. Thank you very much. 🙂

So follow your advise. I should not change my package, which had been published to npm.
