### ISSUE TITLE
There is "Warning: D02 Incompatible package agent-base@5.1.1 found as dependency of axios" message, but that version not in node_module

### ISSUE THREAD

**Issue by jatu-studiobox** [node-red/node-red-dev-cli#20]
My node package use 'axios' version 0.25.0. 

I has checked "agent-base" in node_module folder. Its version is 6.0.2 not 5.1.1.

![image](https://user-images.githubusercontent.com/43282496/152368245-ba0c9da8-7aa5-4dbd-bf94-c086f004d25f.png)

When I run node-red-dev validate locally, there is warning message below.

`Warning: D02 Incompatible package agent-base@5.1.1 found as dependency of axios`

**Comment by sammachin** [comment]
fixed in 0.1.5 https://github.com/node-red/node-red-dev-cli/pull/17
