### ISSUE TITLE
D03: Output lists package versions but not package names

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red-dev-cli#5]
The output of D03 - checking for outdated dependencies - includes an array of package versions, but no information on which packages they relate to. That makes it hard to know what to do next.

```
node_1   | {
node_1   |   test: false,
node_1   |   packages: [
node_1   |     '^0.6.4', '~4.3.2',
node_1   |     '~2.3.0', '^3.5.17',
node_1   |     '^1.4.0', '^4.1.1',
node_1   |     '~1.4.3', '^3.13.1'
node_1   |   ]
node_1   | }
```

**Comment by sammachin** [comment]
fixed in https://github.com/node-red/node-red-dev-cli/commit/6066c840609d1a90c873c5ce472117fa0b1df226

**Comment by sammachin** [comment]
@knolleary can you close this one, I can't.
